/**
 * Utility to convert Quill HTML output to clean, standard Markdown.
 */
export function htmlToMarkdown(html: string): string {
  if (!html) return ''

  let md = html

  // Replace block tags
  md = md.replace(/<h1>(.*?)<\/h1>/gi, '# $1\n\n')
  md = md.replace(/<h2>(.*?)<\/h2>/gi, '## $1\n\n')
  md = md.replace(/<h3>(.*?)<\/h3>/gi, '### $1\n\n')
  md = md.replace(/<h4>(.*?)<\/h4>/gi, '#### $1\n\n')
  
  // Replace code blocks (Quill ql-syntax format)
  md = md.replace(/<pre class="ql-syntax" spellcheck="false">([\s\S]*?)<\/pre>/gi, (_, code) => {
    // Decode HTML entities
    const cleanCode = code
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
    return `\`\`\`\n${cleanCode}\n\`\`\`\n\n`
  })

  // Standard code blocks
  md = md.replace(/<pre><code>([\s\S]*?)<\/code><\/pre>/gi, (_, code) => {
    const cleanCode = code
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
    return `\`\`\`\n${cleanCode}\n\`\`\`\n\n`
  })

  // Inline styling
  md = md.replace(/<strong>(.*?)<\/strong>/gi, '**$1**')
  md = md.replace(/<b>(.*?)<\/b>/gi, '**$1**')
  md = md.replace(/<em>(.*?)<\/em>/gi, '*$1*')
  md = md.replace(/<i>(.*?)<\/i>/gi, '*$1*')
  md = md.replace(/<s>(.*?)<\/s>/gi, '~~$1~~')
  md = md.replace(/<u>(.*?)<\/u>/gi, '<u>$1</u>')
  md = md.replace(/<code>(.*?)<\/code>/gi, '`$1`')

  // Blockquotes
  md = md.replace(/<blockquote>(.*?)<\/blockquote>/gi, '> $1\n\n')

  // Lists
  // Replace list items in ordered lists
  md = md.replace(/<ol>([\s\S]*?)<\/ol>/gi, (_, listContent) => {
    let index = 1
    return listContent.replace(/<li>(.*?)<\/li>/gi, (__: string, item: string) => {
      return `${index++}. ${item}\n`
    }) + '\n'
  })

  // Replace list items in unordered lists
  md = md.replace(/<ul>([\s\S]*?)<\/ul>/gi, (_, listContent) => {
    return listContent.replace(/<li>(.*?)<\/li>/gi, (__: string, item: string) => {
      return `- ${item}\n`
    }) + '\n'
  })

  // Links & Images
  md = md.replace(/<a href="(.*?)">(.*?)<\/a>/gi, '[$2]($1)')
  md = md.replace(/<img src="(.*?)" alt="(.*?)"(.*?)>/gi, '![$2]($1)')
  md = md.replace(/<img src="(.*?)"(.*?)>/gi, '![]($1)')

  // Paragraphs and breaks
  md = md.replace(/<p>(.*?)<\/p>/gi, '$1\n\n')
  md = md.replace(/<br\s*\/?>/gi, '\n')

  // Strip remaining HTML tags
  md = md.replace(/<[^>]+>/g, '')

  // Decode basic HTML entities that might remain
  md = md
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")

  // Remove excessive newlines
  md = md.replace(/\n{3,}/g, '\n\n')

  return md.trim()
}

/**
 * Generate a complete, beautifully structured advisory in Markdown.
 */
export function generateAdvisoryMarkdown(w: any): string {
  const isCve = w.writeup_mode === 'cve'
  const dateStr = new Date(w.created_at).toLocaleDateString('id-ID', { year:'numeric', month:'long', day:'numeric' })
  
  if (!isCve) {
    // Journal Mode markdown
    return `# ${w.title}

- **Platform/Category:** ${w.platform || 'Custom'}
- **Difficulty:** ${w.difficulty || 'Easy'}
- **Date:** ${dateStr}
- **Tags:** ${w.tags || '-'}

## Writeup Content
${htmlToMarkdown(w.content)}
`
  }

  // CVE Mode markdown
  return `# SECURITY ADVISORY | ${w.cve_id || 'PENDING/RESERVED'}
## ${w.title}

---

### METADATA
- **Target Product:** ${w.cve_product || '-'}
- **Affected Version:** ${w.cve_version || '-'}
- **Vulnerability Type:** ${w.cve_cwe || '-'}
- **Date Discovered:** ${dateStr}
- **CVSS v3.1 / 4.0 Score:** ${w.cve_cvss_score ? Number(w.cve_cvss_score).toFixed(1) : '-'} (${w.cve_cvss_severity || 'None'})
- **CVSS Vector:** \`${w.cve_cvss_vector || '-'}\`
- **Tags:** ${w.tags || '-'}

---

### 1. VULNERABILITY SUMMARY
${htmlToMarkdown(w.content)}

### 2. TECHNICAL IMPACT ASSESSMENT
${htmlToMarkdown(w.cve_impact)}

### 3. PROOF OF CONCEPT (PoC)
${htmlToMarkdown(w.cve_poc)}

### 4. REMEDIATION & MITIGATION PLAN
${htmlToMarkdown(w.cve_remediation)}

---
_Generated by HackJournal Professional Security Advisory Generator_
`
}
